# Build project using CMake
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: HorstBaerbel/action-cmake@master
      with:
        sourcedir: '.'
        builddir: 'build'
        cmakeoptions: ''
